### ISSUE TITLE
Imposible Firmar

### ISSUE THREAD

**Issue by gchaincl** [ctt-gob-es/clienteafirma#53]
Hola, estoy intentando firmar unos documentos para presentarlos (o me quedo sin NIE) y no hay forma de hacerlo funcionar. Este es el log de AutoFirma
```
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFO: Las conexiones para protocolo 'http' son por defecto de tipo: DIRECT
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFO: Las conexiones para protocolo 'https' son por defecto de tipo: DIRECT
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.ProxyUtil setProxySettings
INFO: No se usara Proxy para las conexiones de red
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: No se buscaran nuevas versiones de la aplicacion
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFO: Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 4.15.0-34-generic
Version de Java: 10.0.2
Arquitectura del JRE: 64
Java Vendor: Oracle Corporation
Localizacion por defecto: en_US
Tamano actual en memoria: 248MB
Tamano maximo de memoria: 3940MB
Memoria actualmente libre: 234MB
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Apertura como herramienta de escritorio
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Se intenta una precarga temprana de NSS
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFO: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib/thunderbird/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='sql:/USERHOME/.mozilla/firefox/xtwjd55b.default' certPrefix='' keyPrefix='' flags='readOnly'"
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
INFO: NSS necesita una precarga o tratamiento de sus dependencias: java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
WARNING: Ha fallado el segundo intento de carga de NSS: java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.mozilla.NssKeyStoreManager getNssProvider
SEVERE: Error obteniendo el proveedor NSS: java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
	at java.base/java.lang.Class.getConstructor0(Class.java:3302)
	at java.base/java.lang.Class.getConstructor(Class.java:2110)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNssJava8(MozillaKeyStoreUtilities.java:669)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:718)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:111)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:58)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:68)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:488)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:519)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:116)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:571)

Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.KeyStoreUtilities addPreferredKeyStoreManagers
INFO: No se ha encontrado un DNIe: java.security.ProviderException: No se ha podido inicializar el proveedor de DNIe: es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se detectaron lectores de tarjetas en el sistema
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFO: Se incluiran los modulos nativos de DNIe/CERES si se encuentran configurados
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities getMozillaPKCS11Modules
INFO: Obtenidos los modulos externos de Mozilla desde 'pkcs11.txt'
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
INFO: No se han encontrado modulos PKCS#11 externos instalados en Firefox
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma setKeyStoreManager
INFO: Establecido KeyStoreManager: Gestor de almacenes de claves Mozilla / Firefox (unificado) con nombre Mozilla / Firefox (unificado)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by es.gob.afirma.standalone.SimpleAfirma (file:/usr/lib/AutoFirma/AutoFirma.jar) to field sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of es.gob.afirma.standalone.SimpleAfirma
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma loadDefaultKeyStore
INFO: Se omite la carga concurrente de almacen por haberse hecho una precarga previa
Sep 29, 2018 7:06:42 PM es.gob.afirma.keystores.AggregatedKeyStoreManager getAliases
WARNING: No se pudieron obtener los alias del almacen Mozilla / Firefox (unificado): java.lang.IllegalStateException: Se han pedido alias a un almacen no inicializado
Sep 29, 2018 7:06:42 PM es.gob.afirma.standalone.ui.SignPanelSignTask doSignature
SEVERE: El almacen no contiene ningun certificado que se pueda usar para firmar: es.gob.afirma.keystores.AOCertificatesNotFoundException: No se han encontrado certificados en el almacen acordes a los filtros establecidos
```

Intenté hacer los pasos descritos en https://github.com/ctt-gob-es/clienteafirma/issues/16 pero nada.
Uso Ubuntu 18

**Comment by rasputino** [comment]
El log indica que no encuentra el certificado en el almacén. Si el
certificado está en Firefox exportalo a IE (Windows). Si lo tienes en un
lector de tarjetas prueba a instalar el instalador de la fnmt que tiene
también el instalador para el DNI
Un saludo

On Sep 29, 2018 19:10, "Gustavo Chaín" <notifications@github.com> wrote:

Hola, estoy intentando firmar unos documentos para presentarlos (o me quedo
sin NIE) y no hay forma de hacerlo funcionar. Este es el log de AutoFirma

Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFO: Las conexiones para protocolo 'http' son por defecto de tipo: DIRECT
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.ProxyUtil setDefaultProxy
INFO: Las conexiones para protocolo 'https' son por defecto de tipo: DIRECT
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.ProxyUtil setProxySettings
INFO: No se usara Proxy para las conexiones de red
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: No se buscaran nuevas versiones de la aplicacion
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma printSystemInfo
INFO: Resolucion DPI de pantalla: 0
Sistema operativo: Linux
Version del SO: 4.15.0-34-generic
Version de Java: 10.0.2
Arquitectura del JRE: 64
Java Vendor: Oracle Corporation
Localizacion por defecto: en_US
Tamano actual en memoria: 248MB
Tamano maximo de memoria: 3940MB
Memoria actualmente libre: 234MB
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Apertura como herramienta de escritorio
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for
further details.
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma main
INFO: Se intenta una precarga temprana de NSS
Sep 29, 2018 7:04:19 PM
es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNSS
INFO: Configuracion de NSS para SunPKCS11:
name=NSSCrypto-AFirma
library=/usr/lib/thunderbird/libsoftokn3.so
attributes=compatibility
slot=2
showInfo=false
allowSingleThreadedModules=true
nssArgs="configdir='sql:/USERHOME/.mozilla/firefox/xtwjd55b.default'
certPrefix='' keyPrefix='' flags='readOnly'"
Sep 29, 2018 7:04:19 PM
es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
INFO: NSS necesita una precarga o tratamiento de sus dependencias:
java.lang.NoSuchMethodException:
sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
Sep 29, 2018 7:04:19 PM
es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities loadNssJava8
WARNING: Ha fallado el segundo intento de carga de NSS:
java.lang.NoSuchMethodException:
sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
Sep 29, 2018 7:04:19 PM
es.gob.afirma.keystores.mozilla.NssKeyStoreManager getNssProvider
SEVERE: Error obteniendo el proveedor NSS:
java.lang.NoSuchMethodException:
sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
java.lang.NoSuchMethodException:
sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)
	at java.base/java.lang.Class.getConstructor0(Class.java:3302)
	at java.base/java.lang.Class.getConstructor(Class.java:2110)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNssJava8(MozillaKeyStoreUtilities.java:669)
	at es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities.loadNSS(MozillaKeyStoreUtilities.java:718)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.getNssProvider(NssKeyStoreManager.java:111)
	at es.gob.afirma.keystores.mozilla.NssKeyStoreManager.init(NssKeyStoreManager.java:58)
	at es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager.init(MozillaUnifiedKeyStoreManager.java:68)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getNssKeyStoreManager(AOKeyStoreManagerFactory.java:488)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getMozillaUnifiedKeyStoreManager(AOKeyStoreManagerFactory.java:519)
	at es.gob.afirma.keystores.AOKeyStoreManagerFactory.getAOKeyStoreManager(AOKeyStoreManagerFactory.java:116)
	at es.gob.afirma.standalone.SimpleAfirma.main(SimpleAfirma.java:571)

Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.AOKeyStoreManager init
INFO: Inicializamos el almacen de tipo: DNIe y tarjetas FNMT-TIF
Sep 29, 2018 7:04:19 PM es.gob.afirma.keystores.KeyStoreUtilities
addPreferredKeyStoreManagers
INFO: No se ha encontrado un DNIe: java.security.ProviderException: No
se ha podido inicializar el proveedor de DNIe:
es.gob.jmulticard.apdu.connection.NoReadersFoundException: No se
detectaron lectores de tarjetas en el sistema
Sep 29, 2018 7:04:19 PM
es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities
getMozillaPKCS11Modules
INFO: Se incluiran los modulos nativos de DNIe/CERES si se encuentran
configurados
Sep 29, 2018 7:04:19 PM
es.gob.afirma.keystores.mozilla.MozillaKeyStoreUtilities
getMozillaPKCS11Modules
INFO: Obtenidos los modulos externos de Mozilla desde 'pkcs11.txt'
Sep 29, 2018 7:04:19 PM
es.gob.afirma.keystores.mozilla.MozillaUnifiedKeyStoreManager init
INFO: No se han encontrado modulos PKCS#11 externos instalados en Firefox
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma setKeyStoreManager
INFO: Establecido KeyStoreManager: Gestor de almacenes de claves
Mozilla / Firefox (unificado) con nombre Mozilla / Firefox (unificado)
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by
es.gob.afirma.standalone.SimpleAfirma
(file:/usr/lib/AutoFirma/AutoFirma.jar) to field
sun.awt.X11.XToolkit.awtAppClassName
WARNING: Please consider reporting this to the maintainers of
es.gob.afirma.standalone.SimpleAfirma
WARNING: Use --illegal-access=warn to enable warnings of further
illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Sep 29, 2018 7:04:19 PM es.gob.afirma.standalone.SimpleAfirma
loadDefaultKeyStore
INFO: Se omite la carga concurrente de almacen por haberse hecho una
precarga previa
Sep 29, 2018 7:06:42 PM
es.gob.afirma.keystores.AggregatedKeyStoreManager getAliases
WARNING: No se pudieron obtener los alias del almacen Mozilla /
Firefox (unificado): java.lang.IllegalStateException: Se han pedido
alias a un almacen no inicializado
Sep 29, 2018 7:06:42 PM es.gob.afirma.standalone.ui.SignPanelSignTask
doSignature
SEVERE: El almacen no contiene ningun certificado que se pueda usar
para firmar: es.gob.afirma.keystores.AOCertificatesNotFoundException:
No se han encontrado certificados en el almacen acordes a los filtros
establecidos

Intenté hacer los pasos descritos en #16
<https://github.com/ctt-gob-es/clienteafirma/issues/16> pero nada.
Uso Ubuntu 18

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ctt-gob-es/clienteafirma/issues/53>, or mute the thread

**Comment by victorjss** [comment]
El log indica que estás usando la versión 10 de Java:

> Version de Java: 10.0.2

y el error siguiente deja claro que no es compatible con las dependencias 'sun.security.pkcs11' usadas por AutoFirma:

> java.lang.NoSuchMethodException: sun.security.pkcs11.SunPKCS11.<init>(java.io.InputStream)

Hay que configurar Ubuntu para que use Java 8 por defecto.

**Comment by gchaincl** [comment]
Genial @victorjss muchas gracias, funcionó!

**Comment by jgmy** [comment]
Acabo de ver el mensaje anterior buscando solución para persona con el mismo problema. ¿Sois conscientes de que Java 8 está en su End-of-life? ¿Habrá que usar el java del android studio, que es una especie de fork del java 8?

**Comment by gchaincl** [comment]
creo que nadie debería tener que ejecutar esto en su hogar.
no se, digo yo
